### ISSUE TITLE
when to support neo4j 3.0?

### ISSUE THREAD

**Issue by dhcn** [robinedwards/neomodel#213] opened 2016-07-11 09:26 UTC
as title.

**Comment by the4thv** [comment] 2016-07-11 10:02
hi @dhcn , I had intended to have the alpha upgrade ready by this weekend just gone, but there is a lot of re-writing to do. I would say I'm about 60% the way through now, which I hope to finish evening/weekend this week. Then it goes to @nigelsmall to review.

Thanks,

Dave

**Comment by DanJourno** [comment] 2016-07-31 17:37
Hi @the4thv ,
Do you have an ETD for this upgrade? Thanks!

**Comment by the4thv** [comment] 2016-08-01 08:43
Hi @dhcn , sorry for the delay on this, paid work is getting in the way... :( 
I've got a few days off this weekend, so I intend to push on through this. I may well release forked version that is not backward compatible first on my own account. I will update here as soon as I do.

**Comment by dhcn** [comment] 2016-08-09 05:23
@the4thv Many Thanks.

**Comment by DanJourno** [comment] 2016-09-08 14:00
Hi @the4thv,
Thank you for doing the job! Any news about this?

**Comment by the4thv** [comment] 2016-09-09 19:06
Hi @DanJourno, sorry for the delay, I'm still working on it, though nowhere as much as I'd hoped. I'm finishing on a project this week and I will have more time for this then.

**Comment by DanJourno** [comment] 2016-09-11 09:05
@the4thv Thank you very much!

**Comment by ahrennsiva** [comment] 2016-09-15 16:53
@the4thv any updates on expected time to get neomodel working with neo4j v3?

**Comment by the4thv** [comment] 2016-09-17 08:58
Hi @ahrennsiva, paid work has necessarily got in the way, but that should be ending Monday (should have last week!). Once that's the case I will be working on this regularly and hope to get something out within a month or so.

**Comment by prseshad** [comment] 2016-10-14 17:03
Just want to comment that I love neomodel and am using it in production, but we are eager to migrate to neo4j3.  At graph connect right now and am excited about all the new features.  Thanks for working on this, looking forward to the new release!

**Comment by pdonorio** [comment] 2016-10-19 11:43
This is a duplicate of #209 which I opened.
Should I close mine to have only one issue as reference?

**Comment by robinedwards** [comment] 2016-11-21 13:12
I've just pust to master support for neo4j 3 (using the neo4j_driver). I intend to push to pypi in a week or so after i have some feedback and fixed some bugs

**Closed by robinedwards** 2016-11-21 13:12 UTC
